import Foundation

// MARK: - AppleScript helper -------------------------------------------------
func runAppleScript(_ source: String) -> NSAppleEventDescriptor? {
    guard let script = NSAppleScript(source: source) else { return nil }
    var err: NSDictionary?
    return script.executeAndReturnError(&err)
}

// MARK: - Safari tab extraction ---------------------------------------------
struct SafariTab { let title: String; let url: String }

func getSafariTabs() -> [SafariTab] {
    // AppleScript to ask Safari for every window’s tabs
    let appleScript = """
        tell application "Safari"
            set tabInfo to {}
            repeat with w in windows
                repeat with t in tabs of w
                    set tabTitle to name of t
                    set tabURL to URL of t
                    set end of tabInfo to {tabTitle, tabURL}
                end repeat
            end repeat
            return tabInfo
        end tell
    """

    guard let result = runAppleScript(appleScript) else {
        print("❌ AppleScript failed")
        exit(1)
    }

    var tabs: [SafariTab] = []

    // The script returns a list of lists (pairs).  Iterate.
    for i in 1...result.numberOfItems {
        guard let pair = result.atIndex(i) else { continue }
        if let titleDesc = pair.atIndex(1),
           let urlDesc   = pair.atIndex(2),
           let title = titleDesc.stringValue,
           let url   = urlDesc.stringValue
        {
            tabs.append(SafariTab(title: title, url: url))
        }
    }

    return tabs
}

// MARK: - Bookmark file creation --------------------------------------------
func writeBookmarkFile(tabs: [SafariTab]) {
    // 1️⃣ Header
    let header = """
    <!DOCTYPE NETSCAPE-Bookmark-file-1>
    <!-- Automatically generated by SafariTabs.swift -->
    <META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">
    <TITLE>Safari Bookmarks</TITLE>
    <H1>Bookmarks – Auto‑generated by SafariTabs.swift</H1>

    <DL><p>
    """

    // 2️⃣ Entries
    let entries = tabs.map { tab in
        """
        <DT><A HREF=\"\(escapeHTML(tab.url))\" ADD_DATE=\"\(Int(Date().timeIntervalSince1970))\">\(escapeHTML(tab.title))</A>
        """
    }

    // 3️⃣ Footer
    let footer = """
    </DL><p>
    """

    let fullHTML = header + entries.joined(separator: "\n") + "\n" + footer

    // 4️⃣ Write to Desktop with date stamp
    let desktopURL = FileManager.default.urls(for: .desktopDirectory, in: .userDomainMask).first!
    let formatter = DateFormatter()
    formatter.dateFormat = "yyyyMMdd"
    let fileName = "Safari_Bookmarks_\(formatter.string(from: Date())).html"
    let fileURL  = desktopURL.appendingPathComponent(fileName)

    do {
        try fullHTML.write(to: fileURL, atomically: true, encoding: .utf8)
        print("✅ Bookmark file written to \(fileURL.path)")
    } catch {
        fputs("❌ Failed to write bookmark file: \(error)\n", stderr)
        exit(1)
    }
}

// MARK: - Utility ------------------------------------------------------------
func escapeHTML(_ string: String) -> String {
    var escaped = string
    let replacements: [String:String] = [
        "&":"&amp;",
        "<":"&lt;",
        ">":"&gt;",
        "\"":"&quot;",
        "'":"&#39;"
    ]
    for (k,v) in replacements { escaped = escaped.replacingOccurrences(of: k, with: v) }
    return escaped
}

// MARK: - Main ---------------------------------------------------------------
let tabs = getSafariTabs()
writeBookmarkFile(tabs: tabs)