import ArgumentParser
import Foundation
import Cocoa

@main
struct SafariSummary: AsyncParsableCommand {
    static func main() async {
        print("🕵️  Starting Safari summariser…")

        // 1️⃣ Get all tabs using AppleScript (from SafariTabs.swift)
        let tabs = getSafariTabs()
        print("📄 Found \(tabs.count) tabs.")

        // 2️⃣ Process each tab
        var bookmarkEntries: [String] = []
        let decoder = JSONDecoder()

        for (idx, tab) in tabs.enumerated() {
            print("\(idx + 1)/\(tabs.count): Summarising '\(tab.title)'")

            // Call LM Server API with URL
            let reqBody = ChatCompletionRequest(
                model: "gpt-oss-20b",
                messages: [
                    ChatMessage(
                        role: "user",
                        content: "Please provide a concise summary (max 200 characters) of the content at this URL: \(tab.url)"
                    )
                ]
            )
            let apiData: Data
            let summaryResp: ChatCompletionResponse

            do {
                apiData = try await httpPostJSON(url: lmServerURL, body: reqBody, timeout: apiTimeout)
                summaryResp = try decoder.decode(ChatCompletionResponse.self, from: apiData)
            } catch {
                print("⚠️  Summarisation API failed for tab \(tab.url)). Skipping. - \(error.localizedDescription)")
                continue
            }

            let summaryText = truncate(summaryResp.choices.first?.message.content ?? "No summary available", limit: summaryCharLimit)
            
            // Build bookmark <dt>/<dd> pair
            let entryHTML =
                """
                <DT><A HREF="\(escapeHTML(tab.url))" ADD_DATE="\(Int(Date().timeIntervalSince1970))">\(escapeHTML(tab.title))</A>
                <DD><!-- Summary: \(escapeHTML(summaryText)) -->
                """
            bookmarkEntries.append(entryHTML)
        }

        // 3️⃣ Build final HTML
        let header = """
            <!DOCTYPE NETSCAPE-Bookmark-file-1>
            <!-- This is an automatically generated file.
                 It will be read and overwritten by the application that created it. -->
            <META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">
            <TITLE>Safari Bookmarks</TITLE>
            <H1>Bookmarks – Auto‑generated by SafariSummariser</H1>

            <DL><p>
            """
        let footer = """
            </DL><p>
            """

        let fullHTML = header + bookmarkEntries.joined(separator: "\n") + "\n" + footer

        // 4️⃣ Write to Desktop
        let desktopURL = FileManager.default.urls(for: .desktopDirectory, in: .userDomainMask)
            .first!
        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "yyyyMMdd"
        let fileName = "Safari_Bookmarks_\(dateFormatter.string(from: Date())).html"
        let fileURL = desktopURL.appendingPathComponent(fileName)

        do {
            try fullHTML.write(to: fileURL, atomically: true, encoding: .utf8)
            print("✅ Bookmark file written to \(fileURL.path)")
        } catch {
            fputs("❌ Failed to write bookmark file: \(error)\n", stderr)
            Darwin.exit(1)
        }
    }
}

// MARK: - Configuration

let lmServerURL = URL(string: "http://127.0.0.1:1234/v1/chat/completions")!

// Timeout values (seconds)
let apiTimeout = 30.0

// Summary length limit (characters)
let summaryCharLimit = 200

// MARK: - Helper Functions

func httpGet(url: URL, timeout: TimeInterval) async throws -> Data {
    var request = URLRequest(url: url)
    request.httpMethod = "GET"
    request.timeoutInterval = timeout
    let (data, _) = try await URLSession.shared.data(for: request)
    return data
}

func httpPostJSON<T: Encodable>(url: URL, body: T, timeout: TimeInterval) async throws -> Data {
    var request = URLRequest(url: url)
    request.httpMethod = "POST"
    request.timeoutInterval = timeout
    request.setValue("application/json", forHTTPHeaderField: "Content-Type")
    let encoder = JSONEncoder()
    request.httpBody = try encoder.encode(body)
    let (data, _) = try await URLSession.shared.data(for: request)
    return data
}

func escapeHTML(_ string: String) -> String {
    var escaped = string
    let replaceMap: [String: String] = [
        "&": "&amp;",
        "<": "&lt;",
        ">": "&gt;",
        "\"": "&quot;",
    ]
    for (k, v) in replaceMap { escaped = escaped.replacingOccurrences(of: k, with: v) }
    return escaped
}

func truncate(_ string: String, limit: Int) -> String {
    guard string.count > limit else { return string }
    let idx = string.index(string.startIndex, offsetBy: limit)
    return String(string[..<idx]) + "…"
}

func getSafariTabs() -> [TabInfo] {
    // AppleScript to ask Safari for every window’s tabs
    let appleScript = """
            tell application "Safari"
                set tabInfo to {}
                repeat with w in windows
                    repeat with t in tabs of w
                        set tabTitle to name of t
                        set tabURL to URL of t
                        set end of tabInfo to {tabTitle, tabURL}
                    end repeat
                end repeat
                return tabInfo
            end tell
        """

    guard let result = runAppleScript(appleScript) else {
        exit(1)
    }

    var tabs: [TabInfo] = []

    // The script returns a list of lists (pairs).  Iterate.
    for i in 1...result.numberOfItems {
        guard let pair = result.atIndex(i) else { continue }
        if let titleDesc = pair.atIndex(1),
            let urlDesc = pair.atIndex(2),
            let title = titleDesc.stringValue,
            let url = urlDesc.stringValue
        {
            tabs.append(TabInfo(title: title, url: url))
        }
    }

    return tabs
}

func runAppleScript(_ source: String) -> NSAppleEventDescriptor? {
    guard let script = NSAppleScript(source: source) else { return nil }
    var err: NSDictionary?

    print("✅ AppleScript starting")
    let result = script.executeAndReturnError(&err)

    if let error = err {
        print("❌ AppleScript failed: \(error)")
        return nil
    }

    print("✅ AppleScript succeeded")
    return result
}

// MARK: - Data Models

struct TabInfo: Codable {
    let title: String
    let url: String
}

struct WindowTabs: Codable {
    let windows: [Window]
    struct Window: Codable {
        let id: Int
        let tabs: [TabInfo]
    }
}

struct ChatCompletionRequest: Encodable {
    let model: String
    let messages: [ChatMessage]
}

struct ChatMessage: Encodable {
    let role: String
    let content: String
}

struct ChatCompletionResponse: Decodable {
    let choices: [ChatChoice]
}

struct ChatChoice: Decodable {
    let message: ChatMessage
}

extension ChatMessage: Decodable {}